name: Build

on:
  - push

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        target:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.target }}
    steps:
      - uses: actions/checkout@v4

      - uses: mlugg/setup-zig@v1
        with:
          version: master

      - run: cd example && zig build run
